# Generated by Django 5.2.4 on 2025-07-15 06:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_alter_case_case_name_alter_case_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-start_date'], 'verbose_name': 'Case', 'verbose_name_plural': 'Cases'},
        ),
        migrations.RemoveField(
            model_name='case',
            name='modified_date',
        ),
        migrations.AddField(
            model_name='case',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='Set the end date for this case', null=True, verbose_name='End Date'),
        ),
        migrations.AddField(
            model_name='case',
            name='goal_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Set the goal amount in Saudi Riyal', max_digits=10, null=True, verbose_name='Goal Amount (SAR)'),
        ),
        migrations.AddField(
            model_name='case',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Automatically set when case is created', verbose_name='Start Date'),
        ),
    ]
