# Generated by Django 5.2.4 on 2025-07-15 06:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0003_alter_case_options_remove_case_modified_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='end_date',
            field=models.DateField(blank=True, help_text='Set the end date for this case', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='case',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Automatically set when case is created', verbose_name='Start Date'),
        ),
    ]
