# Generated by Django 5.2.4 on 2025-07-15 06:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0003_alter_projectmanagement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmanagement',
            name='end_date',
            field=models.DateField(blank=True, help_text='Set the end date for this project', null=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='projectmanagement',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Automatically set when project is created', verbose_name='Start Date'),
        ),
    ]
