# Generated by Django 5.2.4 on 2025-07-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermanagement',
            options={'ordering': ['-created_date'], 'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
        migrations.RemoveField(
            model_name='ordermanagement',
            name='modified_date',
        ),
        migrations.AlterField(
            model_name='ordermanagement',
            name='gift_template',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Gift Template'),
        ),
        migrations.AlterField(
            model_name='ordermanagement',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='ordermanagement',
            name='recipient_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Recipient Name'),
        ),
        migrations.AlterField(
            model_name='ordermanagement',
            name='sender_name',
            field=models.CharField(max_length=255, verbose_name='Sender Name'),
        ),
    ]
